ItemCollection/Controllers/CollectionController.cs
using ItemCollection.Data;
using ItemCollection.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;

namespace ItemCollection.Controllers
{
    public class CollectionController : Controller
    {
        public ApplicationDbContext _db { get; set; }
        public readonly IWebHostEnvironment _hostEnvironment;

        public CollectionController(ApplicationDbContext db, IWebHostEnvironment hostEnvironment)

        {
            _db = db;
            _hostEnvironment = hostEnvironment;
        }
        public IActionResult Index(int id)
        {
            var obj = _db.Find<Collection>(id);
            var img = _db.Images.Find(obj.Id);
            if (img is null)
            {
                img = new Image();
            }

            obj.Image = img;
            var items = _db.Items.ToList();
            items = items.Where(p => p.CollectionId == obj.Id).ToList();
            obj.ItemList = items;
            var comments = _db.Comments.ToList();
            return View(obj);
        }
        [Authorize]
        public IActionResult DeleteCollection(int id)
        {
            var obj = _db.Find<Collection>(id);
            _db.Remove<Collection>(obj);
            _db.SaveChanges();
            return RedirectToAction("Index", "Home");
        }
        public IActionResult ItemPage(int id)
        {
            var obj = _db.Find<Item>(id);          
            obj.Comments = _db.Comments.Where(p => p.ItemId == obj.Id).ToList();
            obj.ItemTags = _db.Tags.Where(p => p.ItemId == obj.Id).ToList();
            ViewBag.Fields = CheckFields(_db.Find<Collection>(obj.CollectionId));
            return View(obj);
        }
        
        public PartialViewResult GetPartial(int id)
        {
            var item = _db.Find<Item>(id);
            var comments = _db.Comments.ToList();
            return PartialView("_Partial",comments.Where(p => p.ItemId == item.Id));            
        }
        public PartialViewResult OnGetModelPartial()   
        {
            int id = 6;
            var obj = _db.Find<Item>(id);
            var comments = _db.Comments.Where(p => p.ItemId == obj.Id).ToList();
            return new PartialViewResult
            {
                ViewName = "_Partial",
                ViewData = new ViewDataDictionary<List<Comment>>(ViewData, comments)
            };
        }
        [Authorize]
        public IActionResult AddItem(int id)
        {
            var fields = new List<string>();
            var obj = _db.Find<Collection>(id);
            fields = CheckFields(obj);
            ViewBag.Fields = fields;
            return View();
        }
        public JsonResult CommentDetail()
        {
            var comments = _db.Comments.ToList();
           
            return Json(comments);
        }

        public int SaveComment(string comment, int item)
        {
            Comment obj = new Comment();
            obj.Date = DateTime.Now.ToString();
            obj.ItemId = item;
            obj.UserName = User.Identity.Name;
            obj.Description = comment;
            _db.Add<Comment>(obj);
            _db.SaveChanges();
            return 1;
        }
        public List<string> CheckFields(Collection obj)
        {
            var fields = new List<string>();
            if (!(obj.IntFieldOneName is null))
            {
                fields.Add(obj.IntFieldOneName + "(i1)");
            }
            if (!(obj.IntFieldTwoName is null))
            {
                fields.Add(obj.IntFieldTwoName + "(i2)");
            }
            if (!(obj.IntFieldThreeName is null))
            {
                fields.Add(obj.IntFieldThreeName + "(i3)");
            }
            if (!(obj.StringFieldOneName is null))
            {
                fields.Add(obj.StringFieldOneName + "(s1)");
            }
            if (!(obj.StringFieldTwoName is null))
            {
                fields.Add(obj.StringFieldTwoName + "(s2)");
            }
            if (!(obj.StringFieldThreeName is null))
            {
                fields.Add(obj.StringFieldThreeName + "(s3)");
            }
            if (!(obj.BoolFieldOneName is null))
            {
                fields.Add(obj.BoolFieldOneName + "(b1)");
            }
            if (!(obj.BoolFieldTwoName is null))
            {
                fields.Add(obj.BoolFieldTwoName + "(b2)");
            }
            if (!(obj.BoolFieldThreeName is null))
            {
                fields.Add(obj.BoolFieldThreeName + "(b3)");
            }
            return fields;
        }
        [HttpPost]
        public IActionResult AddItem(Item item, int id)
        {
            var obj = _db.Find<Collection>(id);
            
            var tags = item.Tags.Split(' ').ToList();
           
            item.Collection = obj;
            item.Id = 0;
            _db.Items.Add(item);
            
            _db.SaveChanges();
            foreach (var str in tags)
            {
                var tag = new Tag();
                
                tag.ItemId = item.Id;
                tag.TagName = str;
                _db.Tags.Add(tag);
            }
            _db.SaveChanges();
            return RedirectToAction("Index","Home");
        }

    }
}

ItemCollection/Controllers/HomeController.cs
using ItemCollection.Data;
using ItemCollection.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace ItemCollection.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        public ApplicationDbContext _db { get; set; }
        public readonly IWebHostEnvironment _hostEnvironment;

        public HomeController(ILogger<HomeController> logger, ApplicationDbContext db, IWebHostEnvironment hostEnvironment)
        {
            _logger = logger;
            _db = db;
            _hostEnvironment = hostEnvironment;
        }

        public IActionResult Index()
        {
            var collections = _db.Collections.ToList();
            foreach(var obj in collections)
            {
               var img = _db.Images.Find(obj.Id);
                if(img is null)
                {
                    img = new Image();
                }

                obj.Image = img;
            }
            var tags = _db.Tags.ToList();
            var fixedTags = new List<Tag>();
            for (int i =0; i<3; i++)
                {
                fixedTags.Add(tags[new Random().Next(tags.Count)]);
                }
            ViewBag.Tags = fixedTags;
            return View(collections);
        }
        public IActionResult SearchTag(string name)
        {
            var cls = new List<Collection>();
            var tag = _db.Tags.Where(p => p.TagName == name);
            var items = new List<Item>();
            foreach (var obj in tag)
            {
                items.Add(_db.Items.Find(obj.ItemId));
            }
            foreach (var obj in items)
            {
                cls.Add(_db.Collections.Find(obj.CollectionId));
            }
            return View(cls);
        }
        [HttpPost]
        public IActionResult Index(string searchString)
        {
            var collections = _db.Collections.ToList();
            var tags = _db.Tags.ToList();
            var fixedTags = new List<Tag>();
            for (int i = 0; i < 3; i++)
            {
                fixedTags.Add(tags[new Random().Next(tags.Count)]);
            }
            ViewBag.Tags = fixedTags;
            if (!String.IsNullOrEmpty(searchString))
            {
                collections = collections.Where(s => s.Name!.Contains(searchString)).ToList();
            }
            foreach (var obj in collections)
            {
                var img = _db.Images.Find(obj.Id);
                if (img is null)
                {
                    img = new Image();
                }

                obj.Image = img;
            }
            return View(collections);
        }

        public IActionResult AccountPage()
        {
            var collections = _db.Collections.ToList();
            return View(collections);
        }



        public IActionResult Create()
        {

            return View();
        }
        [Authorize]
        [HttpPost]
        public IActionResult Create(Collection obj)
        {

            string wwwPath = _hostEnvironment.WebRootPath;
            string fileName = Path.GetFileNameWithoutExtension(obj.Image.ImageFile.FileName);
            fileName = fileName + DateTime.Now.ToString("yymmssfff") + Path.GetExtension(obj.Image.ImageFile.FileName);
            obj.Image.Name = fileName;
            string path = Path.Combine(wwwPath + "/Image", fileName);
            using (var fileStream = new FileStream(path, FileMode.Create))
            {
                obj.Image.ImageFile.CopyTo(fileStream);
            }
            obj.Owner = User.Identity.Name;
            _db.Collections.Add(obj);
            _db.SaveChanges();
            obj.Image.Name = fileName;
            _db.Update(obj);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ItemCollection/Views/Home/AccountPage.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model List<Collection>

ItemCollection/Views/Home/Create.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model Collection

<form method="post" asp-action="Create" enctype="multipart/form-data">
    <div class="form-group">
        <label for="Cname">Name</label>
        <input asp-for="Name" class="form-control" id="Cname" placeholder="name">
    </div>
    <div class="form-group">
        <label for="topic">Topic</label>
        <select asp-for="Topic" multiple class="form-control" id="topic">
            <option>Books</option>
            <option>Cards</option>
            <option>Coins</option>
            <option>Statuettes</option>
            <option>Magazines</option>
        </select>
    </div>
    <div class="form-group">
        <label for="desc">Description</label>
        <textarea asp-for="Description" class="form-control" id="desc" rows="3"></textarea>
    </div>
    <div class="form-group">
        <label for="Cname">Custom integer fields</label>
        <input asp-for="IntFieldOneName" class="form-control" id="I1name" placeholder="integer field">
    </div>
    <div class="form-group">
        <input asp-for="IntFieldTwoName" class="form-control" id="I1name" placeholder="integer field">
    </div>
    <div class="form-group">
        <input asp-for="IntFieldThreeName" class="form-control" id="I1name" placeholder="integer field">
    </div>
    <div class="form-group">
        <label for="Cname">Custom string fields</label>
        <input asp-for="StringFieldOneName" class="form-control" id="I1name" placeholder="string field">
    </div>
    <div class="form-group">
        <input asp-for="StringFieldTwoName" class="form-control" id="I1name" placeholder="string field">
    </div>
    <div class="form-group">
        <input asp-for="StringFieldThreeName" class="form-control" id="I1name" placeholder="string field">
    </div>
    <div class="form-group">
        <label for="Cname">Custom bool fields</label>
        <input asp-for="BoolFieldOneName" class="form-control" id="I1name" placeholder="bool field">
    </div>
    <div class="form-group">
        <input asp-for="BoolFieldTwoName" class="form-control" id="I1name" placeholder="bool field">
    </div>
    <div class="form-group">
        <input asp-for="BoolFieldThreeName" class="form-control" id="I1name" placeholder="bool field">
    </div>

    <div class="form-group">
        <label for="addfile">Image</label>
        <input type="file" asp-for="Image.ImageFile" accept="image/png,image/jpeg" class="form-control-file" id="exampleFormControlFile1">
    </div>
    <button type="submit" class="btn btn-primary mb-2">Confirm</button>
</form>

ItemCollection/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
@model List<Collection>

    <form asp-controller="Home" asp-action="Index">
        <p>
            Title: <input type="text" name="SearchString" />
            <input type="submit" value="Filter" />
        </p>
    </form>
@foreach(var obj in ViewBag.Tags)
            {
<form asp-controller="Home" asp-action="SearchTag" asp-route-name="@obj.TagName">     
        <input style="display: inline-block;" type="submit" value="@obj.TagName" />
</form>
            }
<div class="row">
    <div class="col-lg-6 col-md-6">
       
        @foreach (var obj in Model)
        {
            <div class="card" style="width: 18rem;">
                <img src="@("/image/" + obj.Image.Name)" class="card-img-top" alt="123">
                <div class="card-body">
                    <h5 class="card-title">@obj.Name</h5>

                    @if (@obj.Description.Length > 50)
                    {
                <p class="card-text">
                    @obj.Description.Substring(0,50) ...
                </p>
                    }
                    else
                {
                <p class="card-text">
                    @obj.Description
                </p>
                }

                <a asp-controller="Collection" asp-action="Index" asp-route-Id="@obj.Id" class="btn btn-primary">Go to collection page</a>
                    </div>
            </div>
        }
    </div>
    @{ 
        Model.Sort((a, b) => a.ItemList.Count.CompareTo(b.ItemList.Count));
    }
<div class="col-lg-6 col-md-6">
    <h5>Коллекции с наибольшим количеством айтемов</h5>
    @foreach (var obj in Model)
    {
        <div class="card" style="width: 18rem;">
            <img src="@("/image/" + obj.Image.Name)" class="card-img-top" alt="123">
            <div class="card-body">
                <h5 class="card-title">@obj.Name</h5>

                @if (@obj.Description.Length > 50)
                {
                    <p class="card-text">
                        @obj.Description.Substring(0, 50) ...
                    </p>
                }
                else
                {
                    <p class="card-text">
                        @obj.Description
                    </p>
                }

            <a asp-controller="Collection" asp-action="Index" asp-route-Id="@obj.Id" class="btn btn-primary">Go to collection page</a>
            </div>
        </div>
    }
</div>
    
    </div>
</div>

ItemCollection/Views/Home/SearchTag.cshtml
@model List<Collection>

@foreach (var obj in Model)
{
    <div class="card" style="width: 18rem;">
        <div class="card-body">
            <h5 class="card-title">@obj.Name</h5>

            @if (@obj.Description.Length > 50)
            {
                <p class="card-text">
                    @obj.Description.Substring(0, 50) ...
                </p>
            }
            else
            {
                <p class="card-text">
                    @obj.Description
                </p>
            }

            <a asp-controller="Collection" asp-action="Index" asp-route-Id="@obj.Id" class="btn btn-primary">Go to collection page</a>
        </div>
    </div>
}